spring:
  data:
    mongodb:
      uri: mongodb+srv://postechfiapprojeto:TOJI49cwoQqGpEvN@fiap.2hmb1.mongodb.net/pagamentos_collection

pedidos:
    service:
        url: http://a9f3a309d03134b829f55baa7cb25c2e-670484907.us-east-1.elb.amazonaws.com